### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by difcareer** [jiyaping/http-proxy-pool#1]
$ gem install http-proxy-pool
ERROR:  Could not find a valid gem 'http-proxy-pool' (>= 0) in any repository
ERROR:  Possible alternatives: http_proxy_pool

hi，我按照提示安装报如上错误，怎么解决？

**Comment by jiyaping** [comment]
@difcareer  sorry。。。看到消息比较晚  
安装应该使用gem install http_proxy_pool
我改一下README
